version: '3.8'

services: 
  postgres:
    image: postgres:13
    container_name: in6am_postgres
    environment:
      POSTGRES_USER: IN6AM
      POSTGRES_PASSWORD: Informatica2026
      POSTGRES_DB: OpiGt
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: